#!/bin/csh

cd /home/pi/rpilights
loop:
wget --quiet http://www.wunderground.com/cgi-bin/findweather/getForecast\?query=55337 > /dev/null
fgrep \"temperature\": getForecast* | cut -d: -f2 | sed 's/[",]//g'| xargs > /home/pi/rpilights/.temperature
fgrep \"condition\": getForecast* | cut -d: -f2 | sed 's/[",]//g' | xargs > /home/pi/rpilights/.forecast
fgrep \"humidity\": getForecast* | cut -d: -f2 | sed 's/[",]//g' | xargs > /home/pi/rpilights/.humidity
rm -f getForecast*
sleep 300
goto loop
