#!/bin/csh

cd /dev/shm
loop:
rm -f .wxdata
curl -s -k "https://api.openweathermap.org/data/2.5/weather?APPID=c182fa7830ca919362fefde7d5ff13f9&zip=55118,us&units=imperial" > .wxdata
set result = `jq -r '.cod' < .wxdata`
if ($result == 200) then
	set result = `jq -r '.main.temp' < .wxdata`
	/usr/bin/printf '%.0f\n' $result > .temperature
	set result = `jq -r '.main.humidity' < .wxdata`
	/usr/bin/printf '%.0f\n' $result > .humidity
	set result = `jq -r '.weather | map (.main) | join (", ")' < .wxdata`
	echo $result > .forecast
endif
sleep 300
goto loop
